// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v6.33.4
// source: tyto/runtime/v1/common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tyto.runtime.v1";

export interface TemplateBinding {
  templateId: string;
  version: string;
  digest: string;
}

/**
 * NetworkPolicy is what a sandbox is allowed to reach.
 *
 * Absent or UNSPECIFIED resolves to STANDARD, so a caller that says nothing
 * keeps the behaviour it already had. That default is deliberate and hard to
 * reverse: once callers build against "sandboxes have internet", tightening
 * it later is a migration, not a config change.
 *
 * TApi validates it; the host compiles it onto the packet filter and never
 * re-derives what the caller asked for.
 */
export interface NetworkPolicy {
  mode: NetworkPolicy_Mode;
  /**
   * allow is honored only in CUSTOM, and rejected in any other mode so a
   * policy cannot look more permissive or more restrictive than it is.
   */
  allow: NetworkRule[];
}

export enum NetworkPolicy_Mode {
  /** NETWORK_MODE_UNSPECIFIED - == STANDARD; the explicit default */
  NETWORK_MODE_UNSPECIFIED = 0,
  /** NETWORK_MODE_STANDARD - public internet via NAT, no lan/guest/metadata */
  NETWORK_MODE_STANDARD = 1,
  /** NETWORK_MODE_DENY_ALL - no egress, including the DNS resolver */
  NETWORK_MODE_DENY_ALL = 2,
  /** NETWORK_MODE_CUSTOM - only allow[] below (+ DNS unless denied) */
  NETWORK_MODE_CUSTOM = 3,
}

export function networkPolicy_ModeFromJSON(object: any): NetworkPolicy_Mode {
  switch (object) {
    case 0:
    case "NETWORK_MODE_UNSPECIFIED":
      return NetworkPolicy_Mode.NETWORK_MODE_UNSPECIFIED;
    case 1:
    case "NETWORK_MODE_STANDARD":
      return NetworkPolicy_Mode.NETWORK_MODE_STANDARD;
    case 2:
    case "NETWORK_MODE_DENY_ALL":
      return NetworkPolicy_Mode.NETWORK_MODE_DENY_ALL;
    case 3:
    case "NETWORK_MODE_CUSTOM":
      return NetworkPolicy_Mode.NETWORK_MODE_CUSTOM;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum NetworkPolicy_Mode");
  }
}

export function networkPolicy_ModeToJSON(object: NetworkPolicy_Mode): string {
  switch (object) {
    case NetworkPolicy_Mode.NETWORK_MODE_UNSPECIFIED:
      return "NETWORK_MODE_UNSPECIFIED";
    case NetworkPolicy_Mode.NETWORK_MODE_STANDARD:
      return "NETWORK_MODE_STANDARD";
    case NetworkPolicy_Mode.NETWORK_MODE_DENY_ALL:
      return "NETWORK_MODE_DENY_ALL";
    case NetworkPolicy_Mode.NETWORK_MODE_CUSTOM:
      return "NETWORK_MODE_CUSTOM";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum NetworkPolicy_Mode");
  }
}

/** NetworkRule is one destination a CUSTOM policy permits. */
export interface NetworkRule {
  /** enforceable on the packet filter today */
  cidr?:
    | string
    | undefined;
  /** rejected at admission until the egress proxy exists */
  domain?:
    | string
    | undefined;
  /** ports is empty for every port on this destination. */
  ports: number[];
}

function createBaseTemplateBinding(): TemplateBinding {
  return { templateId: "", version: "", digest: "" };
}

export const TemplateBinding: MessageFns<TemplateBinding> = {
  encode(message: TemplateBinding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.templateId !== "") {
      writer.uint32(10).string(message.templateId);
    }
    if (message.version !== "") {
      writer.uint32(18).string(message.version);
    }
    if (message.digest !== "") {
      writer.uint32(26).string(message.digest);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemplateBinding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplateBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templateId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.digest = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TemplateBinding {
    return {
      templateId: isSet(object.templateId)
        ? globalThis.String(object.templateId)
        : isSet(object.template_id)
        ? globalThis.String(object.template_id)
        : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      digest: isSet(object.digest) ? globalThis.String(object.digest) : "",
    };
  },

  toJSON(message: TemplateBinding): unknown {
    const obj: any = {};
    if (message.templateId !== "") {
      obj.templateId = message.templateId;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.digest !== "") {
      obj.digest = message.digest;
    }
    return obj;
  },

  create(base?: DeepPartial<TemplateBinding>): TemplateBinding {
    return TemplateBinding.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TemplateBinding>): TemplateBinding {
    const message = createBaseTemplateBinding();
    message.templateId = object.templateId ?? "";
    message.version = object.version ?? "";
    message.digest = object.digest ?? "";
    return message;
  },
};

function createBaseNetworkPolicy(): NetworkPolicy {
  return { mode: 0, allow: [] };
}

export const NetworkPolicy: MessageFns<NetworkPolicy> = {
  encode(message: NetworkPolicy, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mode !== 0) {
      writer.uint32(8).int32(message.mode);
    }
    for (const v of message.allow) {
      NetworkRule.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NetworkPolicy {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkPolicy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.allow.push(NetworkRule.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NetworkPolicy {
    return {
      mode: isSet(object.mode) ? networkPolicy_ModeFromJSON(object.mode) : 0,
      allow: globalThis.Array.isArray(object?.allow) ? object.allow.map((e: any) => NetworkRule.fromJSON(e)) : [],
    };
  },

  toJSON(message: NetworkPolicy): unknown {
    const obj: any = {};
    if (message.mode !== 0) {
      obj.mode = networkPolicy_ModeToJSON(message.mode);
    }
    if (message.allow?.length) {
      obj.allow = message.allow.map((e) => NetworkRule.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<NetworkPolicy>): NetworkPolicy {
    return NetworkPolicy.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NetworkPolicy>): NetworkPolicy {
    const message = createBaseNetworkPolicy();
    message.mode = object.mode ?? 0;
    message.allow = object.allow?.map((e) => NetworkRule.fromPartial(e)) || [];
    return message;
  },
};

function createBaseNetworkRule(): NetworkRule {
  return { cidr: undefined, domain: undefined, ports: [] };
}

export const NetworkRule: MessageFns<NetworkRule> = {
  encode(message: NetworkRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cidr !== undefined) {
      writer.uint32(10).string(message.cidr);
    }
    if (message.domain !== undefined) {
      writer.uint32(18).string(message.domain);
    }
    writer.uint32(26).fork();
    for (const v of message.ports) {
      writer.uint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NetworkRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cidr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.ports.push(reader.uint32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ports.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NetworkRule {
    return {
      cidr: isSet(object.cidr) ? globalThis.String(object.cidr) : undefined,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : undefined,
      ports: globalThis.Array.isArray(object?.ports) ? object.ports.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: NetworkRule): unknown {
    const obj: any = {};
    if (message.cidr !== undefined) {
      obj.cidr = message.cidr;
    }
    if (message.domain !== undefined) {
      obj.domain = message.domain;
    }
    if (message.ports?.length) {
      obj.ports = message.ports.map((e) => Math.round(e));
    }
    return obj;
  },

  create(base?: DeepPartial<NetworkRule>): NetworkRule {
    return NetworkRule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NetworkRule>): NetworkRule {
    const message = createBaseNetworkRule();
    message.cidr = object.cidr ?? undefined;
    message.domain = object.domain ?? undefined;
    message.ports = object.ports?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
