// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v6.33.4
// source: tyto/runtime/v1/host.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Fence } from "./guest.js";
import { PreviewAuthMode, previewAuthModeFromJSON, previewAuthModeToJSON, PreviewRecord } from "./preview.js";

export const protobufPackage = "tyto.runtime.v1";

/**
 * SuspendSource records who asked for a suspend, because preview traffic may
 * wake one kind and must never wake the other: an idle suspend is the platform
 * reclaiming an unused sandbox, while a requested suspend is a deliberate
 * instruction that a public URL must not undo.
 */
export enum SuspendSource {
  SUSPEND_SOURCE_UNSPECIFIED = 0,
  SUSPEND_SOURCE_IDLE = 1,
  SUSPEND_SOURCE_REQUESTED = 2,
}

export function suspendSourceFromJSON(object: any): SuspendSource {
  switch (object) {
    case 0:
    case "SUSPEND_SOURCE_UNSPECIFIED":
      return SuspendSource.SUSPEND_SOURCE_UNSPECIFIED;
    case 1:
    case "SUSPEND_SOURCE_IDLE":
      return SuspendSource.SUSPEND_SOURCE_IDLE;
    case 2:
    case "SUSPEND_SOURCE_REQUESTED":
      return SuspendSource.SUSPEND_SOURCE_REQUESTED;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum SuspendSource");
  }
}

export function suspendSourceToJSON(object: SuspendSource): string {
  switch (object) {
    case SuspendSource.SUSPEND_SOURCE_UNSPECIFIED:
      return "SUSPEND_SOURCE_UNSPECIFIED";
    case SuspendSource.SUSPEND_SOURCE_IDLE:
      return "SUSPEND_SOURCE_IDLE";
    case SuspendSource.SUSPEND_SOURCE_REQUESTED:
      return "SUSPEND_SOURCE_REQUESTED";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum SuspendSource");
  }
}

export interface TemplateBinding {
  templateId: string;
  version: string;
  digest: string;
}

export interface HostBinding {
  hostId: string;
}

export interface CreateRequest {
  operationId: string;
  sandboxId: string;
  hostname: string;
  requestFingerprint: string;
  template: TemplateBinding | undefined;
  host: HostBinding | undefined;
  fence: Fence | undefined;
  tenantId: string;
  /**
   * network is the policy TApi already validated. The host compiles it onto
   * the packet filter; it never re-derives what the caller asked for.
   */
  network: NetworkPolicy | undefined;
}

/**
 * NetworkPolicy is what a sandbox is allowed to reach.
 *
 * It lives here rather than beside the public Create request because the host
 * is what enforces it, and the public API layer imports this file. Absent or
 * UNSPECIFIED resolves to STANDARD, so a caller that says nothing keeps the
 * behaviour it already had. That default is deliberate and hard to reverse:
 * once callers build against "sandboxes have internet", tightening it later is
 * a migration, not a config change.
 */
export interface NetworkPolicy {
  mode: NetworkPolicy_Mode;
  /**
   * allow is honored only in CUSTOM, and rejected in any other mode so a
   * policy cannot look more permissive or more restrictive than it is.
   */
  allow: NetworkRule[];
}

export enum NetworkPolicy_Mode {
  /** NETWORK_MODE_UNSPECIFIED - == STANDARD; the explicit default */
  NETWORK_MODE_UNSPECIFIED = 0,
  /** NETWORK_MODE_STANDARD - public internet via NAT, no lan/guest/metadata */
  NETWORK_MODE_STANDARD = 1,
  /** NETWORK_MODE_DENY_ALL - no egress, including the DNS resolver */
  NETWORK_MODE_DENY_ALL = 2,
  /** NETWORK_MODE_CUSTOM - only allow[] below (+ DNS unless denied) */
  NETWORK_MODE_CUSTOM = 3,
}

export function networkPolicy_ModeFromJSON(object: any): NetworkPolicy_Mode {
  switch (object) {
    case 0:
    case "NETWORK_MODE_UNSPECIFIED":
      return NetworkPolicy_Mode.NETWORK_MODE_UNSPECIFIED;
    case 1:
    case "NETWORK_MODE_STANDARD":
      return NetworkPolicy_Mode.NETWORK_MODE_STANDARD;
    case 2:
    case "NETWORK_MODE_DENY_ALL":
      return NetworkPolicy_Mode.NETWORK_MODE_DENY_ALL;
    case 3:
    case "NETWORK_MODE_CUSTOM":
      return NetworkPolicy_Mode.NETWORK_MODE_CUSTOM;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum NetworkPolicy_Mode");
  }
}

export function networkPolicy_ModeToJSON(object: NetworkPolicy_Mode): string {
  switch (object) {
    case NetworkPolicy_Mode.NETWORK_MODE_UNSPECIFIED:
      return "NETWORK_MODE_UNSPECIFIED";
    case NetworkPolicy_Mode.NETWORK_MODE_STANDARD:
      return "NETWORK_MODE_STANDARD";
    case NetworkPolicy_Mode.NETWORK_MODE_DENY_ALL:
      return "NETWORK_MODE_DENY_ALL";
    case NetworkPolicy_Mode.NETWORK_MODE_CUSTOM:
      return "NETWORK_MODE_CUSTOM";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum NetworkPolicy_Mode");
  }
}

/** NetworkRule is one destination a CUSTOM policy permits. */
export interface NetworkRule {
  /** enforceable on the packet filter today */
  cidr?:
    | string
    | undefined;
  /** rejected at admission until the egress proxy exists */
  domain?:
    | string
    | undefined;
  /** ports is empty for every port on this destination. */
  ports: number[];
}

export interface CreateResponse {
  operationId: string;
  sandboxId: string;
  hostId: string;
  requestFingerprint: string;
  fence: Fence | undefined;
}

export interface HostDeleteRequest {
  tenantId: string;
  sandboxId: string;
  hostId: string;
}

export interface HostSuspendRequest {
  tenantId: string;
  sandboxId: string;
  hostId: string;
  lifecycleOperationId: string;
  /**
   * Rejected when unset: defaulting either way is wrong. Defaulting to idle
   * would let preview traffic wake a sandbox someone deliberately suspended;
   * defaulting to requested would silently disable wake-on-access.
   */
  source: SuspendSource;
}

export interface HostSuspendResponse {
  sandboxId: string;
  lifecycleOperationId: string;
  alreadySuspended: boolean;
  appliedSuspendFence: Fence | undefined;
}

export interface HostResumeRequest {
  tenantId: string;
  sandboxId: string;
  hostId: string;
  lifecycleOperationId: string;
}

export interface HostResumeResponse {
  sandboxId: string;
  lifecycleOperationId: string;
  alreadyRunning: boolean;
  appliedResumeFence: Fence | undefined;
}

export interface HostCreateSnapshotRequest {
  tenantId: string;
  sourceSandboxId: string;
  hostId: string;
  snapshotId: string;
}

export interface HostCreateSnapshotResponse {
  snapshotId: string;
  sourceSandboxId: string;
  alreadyCreated: boolean;
}

export interface HostDeleteSnapshotRequest {
  tenantId: string;
  sourceSandboxId: string;
  hostId: string;
  snapshotId: string;
}

export interface HostDeleteSnapshotResponse {
  snapshotId: string;
}

export interface HostDeleteResponse {
  sandboxId: string;
  alreadyDeleted: boolean;
  appliedRetirementFence: Fence | undefined;
}

export interface HostCreatePreviewRequest {
  tenantId: string;
  sandboxId: string;
  hostId: string;
  /** preview_id is minted by TApi, so ids stay unique across hosts. */
  previewId: string;
  port: number;
  authMode: PreviewAuthMode;
  name: string;
  /**
   * idempotency_key makes a retried create return the original preview rather
   * than minting a second one. It is journaled by Nestled and never published
   * to Roxy, which has no use for it.
   */
  idempotencyKey: string;
}

export interface HostCreatePreviewResponse {
  preview: PreviewRecord | undefined;
}

export interface HostDeletePreviewRequest {
  tenantId: string;
  sandboxId: string;
  hostId: string;
  previewId: string;
}

export interface HostDeletePreviewResponse {
  previewId: string;
  /**
   * already_deleted is true only once the removal is confirmed published, so a
   * caller that sees it knows the preview is genuinely unreachable.
   */
  alreadyDeleted: boolean;
}

export interface HostListPreviewsRequest {
  tenantId: string;
  sandboxId: string;
  hostId: string;
}

export interface HostListPreviewsResponse {
  previews: PreviewRecord[];
}

function createBaseTemplateBinding(): TemplateBinding {
  return { templateId: "", version: "", digest: "" };
}

export const TemplateBinding: MessageFns<TemplateBinding> = {
  encode(message: TemplateBinding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.templateId !== "") {
      writer.uint32(10).string(message.templateId);
    }
    if (message.version !== "") {
      writer.uint32(18).string(message.version);
    }
    if (message.digest !== "") {
      writer.uint32(26).string(message.digest);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemplateBinding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplateBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templateId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.digest = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TemplateBinding {
    return {
      templateId: isSet(object.templateId)
        ? globalThis.String(object.templateId)
        : isSet(object.template_id)
        ? globalThis.String(object.template_id)
        : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      digest: isSet(object.digest) ? globalThis.String(object.digest) : "",
    };
  },

  toJSON(message: TemplateBinding): unknown {
    const obj: any = {};
    if (message.templateId !== "") {
      obj.templateId = message.templateId;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.digest !== "") {
      obj.digest = message.digest;
    }
    return obj;
  },

  create(base?: DeepPartial<TemplateBinding>): TemplateBinding {
    return TemplateBinding.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TemplateBinding>): TemplateBinding {
    const message = createBaseTemplateBinding();
    message.templateId = object.templateId ?? "";
    message.version = object.version ?? "";
    message.digest = object.digest ?? "";
    return message;
  },
};

function createBaseHostBinding(): HostBinding {
  return { hostId: "" };
}

export const HostBinding: MessageFns<HostBinding> = {
  encode(message: HostBinding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hostId !== "") {
      writer.uint32(10).string(message.hostId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostBinding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostBinding {
    return {
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
    };
  },

  toJSON(message: HostBinding): unknown {
    const obj: any = {};
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    return obj;
  },

  create(base?: DeepPartial<HostBinding>): HostBinding {
    return HostBinding.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostBinding>): HostBinding {
    const message = createBaseHostBinding();
    message.hostId = object.hostId ?? "";
    return message;
  },
};

function createBaseCreateRequest(): CreateRequest {
  return {
    operationId: "",
    sandboxId: "",
    hostname: "",
    requestFingerprint: "",
    template: undefined,
    host: undefined,
    fence: undefined,
    tenantId: "",
    network: undefined,
  };
}

export const CreateRequest: MessageFns<CreateRequest> = {
  encode(message: CreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operationId !== "") {
      writer.uint32(10).string(message.operationId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.hostname !== "") {
      writer.uint32(26).string(message.hostname);
    }
    if (message.requestFingerprint !== "") {
      writer.uint32(34).string(message.requestFingerprint);
    }
    if (message.template !== undefined) {
      TemplateBinding.encode(message.template, writer.uint32(42).fork()).join();
    }
    if (message.host !== undefined) {
      HostBinding.encode(message.host, writer.uint32(50).fork()).join();
    }
    if (message.fence !== undefined) {
      Fence.encode(message.fence, writer.uint32(58).fork()).join();
    }
    if (message.tenantId !== "") {
      writer.uint32(66).string(message.tenantId);
    }
    if (message.network !== undefined) {
      NetworkPolicy.encode(message.network, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostname = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.requestFingerprint = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.template = TemplateBinding.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.host = HostBinding.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.fence = Fence.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.network = NetworkPolicy.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateRequest {
    return {
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "",
      requestFingerprint: isSet(object.requestFingerprint)
        ? globalThis.String(object.requestFingerprint)
        : isSet(object.request_fingerprint)
        ? globalThis.String(object.request_fingerprint)
        : "",
      template: isSet(object.template) ? TemplateBinding.fromJSON(object.template) : undefined,
      host: isSet(object.host) ? HostBinding.fromJSON(object.host) : undefined,
      fence: isSet(object.fence) ? Fence.fromJSON(object.fence) : undefined,
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      network: isSet(object.network) ? NetworkPolicy.fromJSON(object.network) : undefined,
    };
  },

  toJSON(message: CreateRequest): unknown {
    const obj: any = {};
    if (message.operationId !== "") {
      obj.operationId = message.operationId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    if (message.requestFingerprint !== "") {
      obj.requestFingerprint = message.requestFingerprint;
    }
    if (message.template !== undefined) {
      obj.template = TemplateBinding.toJSON(message.template);
    }
    if (message.host !== undefined) {
      obj.host = HostBinding.toJSON(message.host);
    }
    if (message.fence !== undefined) {
      obj.fence = Fence.toJSON(message.fence);
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.network !== undefined) {
      obj.network = NetworkPolicy.toJSON(message.network);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateRequest>): CreateRequest {
    return CreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateRequest>): CreateRequest {
    const message = createBaseCreateRequest();
    message.operationId = object.operationId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.hostname = object.hostname ?? "";
    message.requestFingerprint = object.requestFingerprint ?? "";
    message.template = (object.template !== undefined && object.template !== null)
      ? TemplateBinding.fromPartial(object.template)
      : undefined;
    message.host = (object.host !== undefined && object.host !== null)
      ? HostBinding.fromPartial(object.host)
      : undefined;
    message.fence = (object.fence !== undefined && object.fence !== null) ? Fence.fromPartial(object.fence) : undefined;
    message.tenantId = object.tenantId ?? "";
    message.network = (object.network !== undefined && object.network !== null)
      ? NetworkPolicy.fromPartial(object.network)
      : undefined;
    return message;
  },
};

function createBaseNetworkPolicy(): NetworkPolicy {
  return { mode: 0, allow: [] };
}

export const NetworkPolicy: MessageFns<NetworkPolicy> = {
  encode(message: NetworkPolicy, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mode !== 0) {
      writer.uint32(8).int32(message.mode);
    }
    for (const v of message.allow) {
      NetworkRule.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NetworkPolicy {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkPolicy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.allow.push(NetworkRule.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NetworkPolicy {
    return {
      mode: isSet(object.mode) ? networkPolicy_ModeFromJSON(object.mode) : 0,
      allow: globalThis.Array.isArray(object?.allow) ? object.allow.map((e: any) => NetworkRule.fromJSON(e)) : [],
    };
  },

  toJSON(message: NetworkPolicy): unknown {
    const obj: any = {};
    if (message.mode !== 0) {
      obj.mode = networkPolicy_ModeToJSON(message.mode);
    }
    if (message.allow?.length) {
      obj.allow = message.allow.map((e) => NetworkRule.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<NetworkPolicy>): NetworkPolicy {
    return NetworkPolicy.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NetworkPolicy>): NetworkPolicy {
    const message = createBaseNetworkPolicy();
    message.mode = object.mode ?? 0;
    message.allow = object.allow?.map((e) => NetworkRule.fromPartial(e)) || [];
    return message;
  },
};

function createBaseNetworkRule(): NetworkRule {
  return { cidr: undefined, domain: undefined, ports: [] };
}

export const NetworkRule: MessageFns<NetworkRule> = {
  encode(message: NetworkRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cidr !== undefined) {
      writer.uint32(10).string(message.cidr);
    }
    if (message.domain !== undefined) {
      writer.uint32(18).string(message.domain);
    }
    writer.uint32(26).fork();
    for (const v of message.ports) {
      writer.uint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NetworkRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cidr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.ports.push(reader.uint32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ports.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NetworkRule {
    return {
      cidr: isSet(object.cidr) ? globalThis.String(object.cidr) : undefined,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : undefined,
      ports: globalThis.Array.isArray(object?.ports) ? object.ports.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: NetworkRule): unknown {
    const obj: any = {};
    if (message.cidr !== undefined) {
      obj.cidr = message.cidr;
    }
    if (message.domain !== undefined) {
      obj.domain = message.domain;
    }
    if (message.ports?.length) {
      obj.ports = message.ports.map((e) => Math.round(e));
    }
    return obj;
  },

  create(base?: DeepPartial<NetworkRule>): NetworkRule {
    return NetworkRule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NetworkRule>): NetworkRule {
    const message = createBaseNetworkRule();
    message.cidr = object.cidr ?? undefined;
    message.domain = object.domain ?? undefined;
    message.ports = object.ports?.map((e) => e) || [];
    return message;
  },
};

function createBaseCreateResponse(): CreateResponse {
  return { operationId: "", sandboxId: "", hostId: "", requestFingerprint: "", fence: undefined };
}

export const CreateResponse: MessageFns<CreateResponse> = {
  encode(message: CreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operationId !== "") {
      writer.uint32(10).string(message.operationId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    if (message.requestFingerprint !== "") {
      writer.uint32(34).string(message.requestFingerprint);
    }
    if (message.fence !== undefined) {
      Fence.encode(message.fence, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.requestFingerprint = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fence = Fence.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateResponse {
    return {
      operationId: isSet(object.operationId)
        ? globalThis.String(object.operationId)
        : isSet(object.operation_id)
        ? globalThis.String(object.operation_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
      requestFingerprint: isSet(object.requestFingerprint)
        ? globalThis.String(object.requestFingerprint)
        : isSet(object.request_fingerprint)
        ? globalThis.String(object.request_fingerprint)
        : "",
      fence: isSet(object.fence) ? Fence.fromJSON(object.fence) : undefined,
    };
  },

  toJSON(message: CreateResponse): unknown {
    const obj: any = {};
    if (message.operationId !== "") {
      obj.operationId = message.operationId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    if (message.requestFingerprint !== "") {
      obj.requestFingerprint = message.requestFingerprint;
    }
    if (message.fence !== undefined) {
      obj.fence = Fence.toJSON(message.fence);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateResponse>): CreateResponse {
    return CreateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateResponse>): CreateResponse {
    const message = createBaseCreateResponse();
    message.operationId = object.operationId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.hostId = object.hostId ?? "";
    message.requestFingerprint = object.requestFingerprint ?? "";
    message.fence = (object.fence !== undefined && object.fence !== null) ? Fence.fromPartial(object.fence) : undefined;
    return message;
  },
};

function createBaseHostDeleteRequest(): HostDeleteRequest {
  return { tenantId: "", sandboxId: "", hostId: "" };
}

export const HostDeleteRequest: MessageFns<HostDeleteRequest> = {
  encode(message: HostDeleteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostDeleteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostDeleteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostDeleteRequest {
    return {
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
    };
  },

  toJSON(message: HostDeleteRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    return obj;
  },

  create(base?: DeepPartial<HostDeleteRequest>): HostDeleteRequest {
    return HostDeleteRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostDeleteRequest>): HostDeleteRequest {
    const message = createBaseHostDeleteRequest();
    message.tenantId = object.tenantId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.hostId = object.hostId ?? "";
    return message;
  },
};

function createBaseHostSuspendRequest(): HostSuspendRequest {
  return { tenantId: "", sandboxId: "", hostId: "", lifecycleOperationId: "", source: 0 };
}

export const HostSuspendRequest: MessageFns<HostSuspendRequest> = {
  encode(message: HostSuspendRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    if (message.lifecycleOperationId !== "") {
      writer.uint32(34).string(message.lifecycleOperationId);
    }
    if (message.source !== 0) {
      writer.uint32(40).int32(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostSuspendRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostSuspendRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lifecycleOperationId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.source = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostSuspendRequest {
    return {
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
      lifecycleOperationId: isSet(object.lifecycleOperationId)
        ? globalThis.String(object.lifecycleOperationId)
        : isSet(object.lifecycle_operation_id)
        ? globalThis.String(object.lifecycle_operation_id)
        : "",
      source: isSet(object.source) ? suspendSourceFromJSON(object.source) : 0,
    };
  },

  toJSON(message: HostSuspendRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    if (message.lifecycleOperationId !== "") {
      obj.lifecycleOperationId = message.lifecycleOperationId;
    }
    if (message.source !== 0) {
      obj.source = suspendSourceToJSON(message.source);
    }
    return obj;
  },

  create(base?: DeepPartial<HostSuspendRequest>): HostSuspendRequest {
    return HostSuspendRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostSuspendRequest>): HostSuspendRequest {
    const message = createBaseHostSuspendRequest();
    message.tenantId = object.tenantId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.hostId = object.hostId ?? "";
    message.lifecycleOperationId = object.lifecycleOperationId ?? "";
    message.source = object.source ?? 0;
    return message;
  },
};

function createBaseHostSuspendResponse(): HostSuspendResponse {
  return { sandboxId: "", lifecycleOperationId: "", alreadySuspended: false, appliedSuspendFence: undefined };
}

export const HostSuspendResponse: MessageFns<HostSuspendResponse> = {
  encode(message: HostSuspendResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    if (message.lifecycleOperationId !== "") {
      writer.uint32(18).string(message.lifecycleOperationId);
    }
    if (message.alreadySuspended !== false) {
      writer.uint32(24).bool(message.alreadySuspended);
    }
    if (message.appliedSuspendFence !== undefined) {
      Fence.encode(message.appliedSuspendFence, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostSuspendResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostSuspendResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lifecycleOperationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.alreadySuspended = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.appliedSuspendFence = Fence.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostSuspendResponse {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      lifecycleOperationId: isSet(object.lifecycleOperationId)
        ? globalThis.String(object.lifecycleOperationId)
        : isSet(object.lifecycle_operation_id)
        ? globalThis.String(object.lifecycle_operation_id)
        : "",
      alreadySuspended: isSet(object.alreadySuspended)
        ? globalThis.Boolean(object.alreadySuspended)
        : isSet(object.already_suspended)
        ? globalThis.Boolean(object.already_suspended)
        : false,
      appliedSuspendFence: isSet(object.appliedSuspendFence)
        ? Fence.fromJSON(object.appliedSuspendFence)
        : isSet(object.applied_suspend_fence)
        ? Fence.fromJSON(object.applied_suspend_fence)
        : undefined,
    };
  },

  toJSON(message: HostSuspendResponse): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.lifecycleOperationId !== "") {
      obj.lifecycleOperationId = message.lifecycleOperationId;
    }
    if (message.alreadySuspended !== false) {
      obj.alreadySuspended = message.alreadySuspended;
    }
    if (message.appliedSuspendFence !== undefined) {
      obj.appliedSuspendFence = Fence.toJSON(message.appliedSuspendFence);
    }
    return obj;
  },

  create(base?: DeepPartial<HostSuspendResponse>): HostSuspendResponse {
    return HostSuspendResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostSuspendResponse>): HostSuspendResponse {
    const message = createBaseHostSuspendResponse();
    message.sandboxId = object.sandboxId ?? "";
    message.lifecycleOperationId = object.lifecycleOperationId ?? "";
    message.alreadySuspended = object.alreadySuspended ?? false;
    message.appliedSuspendFence = (object.appliedSuspendFence !== undefined && object.appliedSuspendFence !== null)
      ? Fence.fromPartial(object.appliedSuspendFence)
      : undefined;
    return message;
  },
};

function createBaseHostResumeRequest(): HostResumeRequest {
  return { tenantId: "", sandboxId: "", hostId: "", lifecycleOperationId: "" };
}

export const HostResumeRequest: MessageFns<HostResumeRequest> = {
  encode(message: HostResumeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    if (message.lifecycleOperationId !== "") {
      writer.uint32(34).string(message.lifecycleOperationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostResumeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostResumeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lifecycleOperationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostResumeRequest {
    return {
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
      lifecycleOperationId: isSet(object.lifecycleOperationId)
        ? globalThis.String(object.lifecycleOperationId)
        : isSet(object.lifecycle_operation_id)
        ? globalThis.String(object.lifecycle_operation_id)
        : "",
    };
  },

  toJSON(message: HostResumeRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    if (message.lifecycleOperationId !== "") {
      obj.lifecycleOperationId = message.lifecycleOperationId;
    }
    return obj;
  },

  create(base?: DeepPartial<HostResumeRequest>): HostResumeRequest {
    return HostResumeRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostResumeRequest>): HostResumeRequest {
    const message = createBaseHostResumeRequest();
    message.tenantId = object.tenantId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.hostId = object.hostId ?? "";
    message.lifecycleOperationId = object.lifecycleOperationId ?? "";
    return message;
  },
};

function createBaseHostResumeResponse(): HostResumeResponse {
  return { sandboxId: "", lifecycleOperationId: "", alreadyRunning: false, appliedResumeFence: undefined };
}

export const HostResumeResponse: MessageFns<HostResumeResponse> = {
  encode(message: HostResumeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    if (message.lifecycleOperationId !== "") {
      writer.uint32(18).string(message.lifecycleOperationId);
    }
    if (message.alreadyRunning !== false) {
      writer.uint32(24).bool(message.alreadyRunning);
    }
    if (message.appliedResumeFence !== undefined) {
      Fence.encode(message.appliedResumeFence, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostResumeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostResumeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lifecycleOperationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.alreadyRunning = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.appliedResumeFence = Fence.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostResumeResponse {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      lifecycleOperationId: isSet(object.lifecycleOperationId)
        ? globalThis.String(object.lifecycleOperationId)
        : isSet(object.lifecycle_operation_id)
        ? globalThis.String(object.lifecycle_operation_id)
        : "",
      alreadyRunning: isSet(object.alreadyRunning)
        ? globalThis.Boolean(object.alreadyRunning)
        : isSet(object.already_running)
        ? globalThis.Boolean(object.already_running)
        : false,
      appliedResumeFence: isSet(object.appliedResumeFence)
        ? Fence.fromJSON(object.appliedResumeFence)
        : isSet(object.applied_resume_fence)
        ? Fence.fromJSON(object.applied_resume_fence)
        : undefined,
    };
  },

  toJSON(message: HostResumeResponse): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.lifecycleOperationId !== "") {
      obj.lifecycleOperationId = message.lifecycleOperationId;
    }
    if (message.alreadyRunning !== false) {
      obj.alreadyRunning = message.alreadyRunning;
    }
    if (message.appliedResumeFence !== undefined) {
      obj.appliedResumeFence = Fence.toJSON(message.appliedResumeFence);
    }
    return obj;
  },

  create(base?: DeepPartial<HostResumeResponse>): HostResumeResponse {
    return HostResumeResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostResumeResponse>): HostResumeResponse {
    const message = createBaseHostResumeResponse();
    message.sandboxId = object.sandboxId ?? "";
    message.lifecycleOperationId = object.lifecycleOperationId ?? "";
    message.alreadyRunning = object.alreadyRunning ?? false;
    message.appliedResumeFence = (object.appliedResumeFence !== undefined && object.appliedResumeFence !== null)
      ? Fence.fromPartial(object.appliedResumeFence)
      : undefined;
    return message;
  },
};

function createBaseHostCreateSnapshotRequest(): HostCreateSnapshotRequest {
  return { tenantId: "", sourceSandboxId: "", hostId: "", snapshotId: "" };
}

export const HostCreateSnapshotRequest: MessageFns<HostCreateSnapshotRequest> = {
  encode(message: HostCreateSnapshotRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.sourceSandboxId !== "") {
      writer.uint32(18).string(message.sourceSandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    if (message.snapshotId !== "") {
      writer.uint32(34).string(message.snapshotId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostCreateSnapshotRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostCreateSnapshotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceSandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.snapshotId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostCreateSnapshotRequest {
    return {
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      sourceSandboxId: isSet(object.sourceSandboxId)
        ? globalThis.String(object.sourceSandboxId)
        : isSet(object.source_sandbox_id)
        ? globalThis.String(object.source_sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
      snapshotId: isSet(object.snapshotId)
        ? globalThis.String(object.snapshotId)
        : isSet(object.snapshot_id)
        ? globalThis.String(object.snapshot_id)
        : "",
    };
  },

  toJSON(message: HostCreateSnapshotRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.sourceSandboxId !== "") {
      obj.sourceSandboxId = message.sourceSandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    if (message.snapshotId !== "") {
      obj.snapshotId = message.snapshotId;
    }
    return obj;
  },

  create(base?: DeepPartial<HostCreateSnapshotRequest>): HostCreateSnapshotRequest {
    return HostCreateSnapshotRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostCreateSnapshotRequest>): HostCreateSnapshotRequest {
    const message = createBaseHostCreateSnapshotRequest();
    message.tenantId = object.tenantId ?? "";
    message.sourceSandboxId = object.sourceSandboxId ?? "";
    message.hostId = object.hostId ?? "";
    message.snapshotId = object.snapshotId ?? "";
    return message;
  },
};

function createBaseHostCreateSnapshotResponse(): HostCreateSnapshotResponse {
  return { snapshotId: "", sourceSandboxId: "", alreadyCreated: false };
}

export const HostCreateSnapshotResponse: MessageFns<HostCreateSnapshotResponse> = {
  encode(message: HostCreateSnapshotResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.snapshotId !== "") {
      writer.uint32(10).string(message.snapshotId);
    }
    if (message.sourceSandboxId !== "") {
      writer.uint32(18).string(message.sourceSandboxId);
    }
    if (message.alreadyCreated !== false) {
      writer.uint32(24).bool(message.alreadyCreated);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostCreateSnapshotResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostCreateSnapshotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.snapshotId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceSandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.alreadyCreated = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostCreateSnapshotResponse {
    return {
      snapshotId: isSet(object.snapshotId)
        ? globalThis.String(object.snapshotId)
        : isSet(object.snapshot_id)
        ? globalThis.String(object.snapshot_id)
        : "",
      sourceSandboxId: isSet(object.sourceSandboxId)
        ? globalThis.String(object.sourceSandboxId)
        : isSet(object.source_sandbox_id)
        ? globalThis.String(object.source_sandbox_id)
        : "",
      alreadyCreated: isSet(object.alreadyCreated)
        ? globalThis.Boolean(object.alreadyCreated)
        : isSet(object.already_created)
        ? globalThis.Boolean(object.already_created)
        : false,
    };
  },

  toJSON(message: HostCreateSnapshotResponse): unknown {
    const obj: any = {};
    if (message.snapshotId !== "") {
      obj.snapshotId = message.snapshotId;
    }
    if (message.sourceSandboxId !== "") {
      obj.sourceSandboxId = message.sourceSandboxId;
    }
    if (message.alreadyCreated !== false) {
      obj.alreadyCreated = message.alreadyCreated;
    }
    return obj;
  },

  create(base?: DeepPartial<HostCreateSnapshotResponse>): HostCreateSnapshotResponse {
    return HostCreateSnapshotResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostCreateSnapshotResponse>): HostCreateSnapshotResponse {
    const message = createBaseHostCreateSnapshotResponse();
    message.snapshotId = object.snapshotId ?? "";
    message.sourceSandboxId = object.sourceSandboxId ?? "";
    message.alreadyCreated = object.alreadyCreated ?? false;
    return message;
  },
};

function createBaseHostDeleteSnapshotRequest(): HostDeleteSnapshotRequest {
  return { tenantId: "", sourceSandboxId: "", hostId: "", snapshotId: "" };
}

export const HostDeleteSnapshotRequest: MessageFns<HostDeleteSnapshotRequest> = {
  encode(message: HostDeleteSnapshotRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.sourceSandboxId !== "") {
      writer.uint32(18).string(message.sourceSandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    if (message.snapshotId !== "") {
      writer.uint32(34).string(message.snapshotId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostDeleteSnapshotRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostDeleteSnapshotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceSandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.snapshotId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostDeleteSnapshotRequest {
    return {
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      sourceSandboxId: isSet(object.sourceSandboxId)
        ? globalThis.String(object.sourceSandboxId)
        : isSet(object.source_sandbox_id)
        ? globalThis.String(object.source_sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
      snapshotId: isSet(object.snapshotId)
        ? globalThis.String(object.snapshotId)
        : isSet(object.snapshot_id)
        ? globalThis.String(object.snapshot_id)
        : "",
    };
  },

  toJSON(message: HostDeleteSnapshotRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.sourceSandboxId !== "") {
      obj.sourceSandboxId = message.sourceSandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    if (message.snapshotId !== "") {
      obj.snapshotId = message.snapshotId;
    }
    return obj;
  },

  create(base?: DeepPartial<HostDeleteSnapshotRequest>): HostDeleteSnapshotRequest {
    return HostDeleteSnapshotRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostDeleteSnapshotRequest>): HostDeleteSnapshotRequest {
    const message = createBaseHostDeleteSnapshotRequest();
    message.tenantId = object.tenantId ?? "";
    message.sourceSandboxId = object.sourceSandboxId ?? "";
    message.hostId = object.hostId ?? "";
    message.snapshotId = object.snapshotId ?? "";
    return message;
  },
};

function createBaseHostDeleteSnapshotResponse(): HostDeleteSnapshotResponse {
  return { snapshotId: "" };
}

export const HostDeleteSnapshotResponse: MessageFns<HostDeleteSnapshotResponse> = {
  encode(message: HostDeleteSnapshotResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.snapshotId !== "") {
      writer.uint32(10).string(message.snapshotId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostDeleteSnapshotResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostDeleteSnapshotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.snapshotId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostDeleteSnapshotResponse {
    return {
      snapshotId: isSet(object.snapshotId)
        ? globalThis.String(object.snapshotId)
        : isSet(object.snapshot_id)
        ? globalThis.String(object.snapshot_id)
        : "",
    };
  },

  toJSON(message: HostDeleteSnapshotResponse): unknown {
    const obj: any = {};
    if (message.snapshotId !== "") {
      obj.snapshotId = message.snapshotId;
    }
    return obj;
  },

  create(base?: DeepPartial<HostDeleteSnapshotResponse>): HostDeleteSnapshotResponse {
    return HostDeleteSnapshotResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostDeleteSnapshotResponse>): HostDeleteSnapshotResponse {
    const message = createBaseHostDeleteSnapshotResponse();
    message.snapshotId = object.snapshotId ?? "";
    return message;
  },
};

function createBaseHostDeleteResponse(): HostDeleteResponse {
  return { sandboxId: "", alreadyDeleted: false, appliedRetirementFence: undefined };
}

export const HostDeleteResponse: MessageFns<HostDeleteResponse> = {
  encode(message: HostDeleteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    if (message.alreadyDeleted !== false) {
      writer.uint32(16).bool(message.alreadyDeleted);
    }
    if (message.appliedRetirementFence !== undefined) {
      Fence.encode(message.appliedRetirementFence, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostDeleteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostDeleteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.alreadyDeleted = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.appliedRetirementFence = Fence.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostDeleteResponse {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      alreadyDeleted: isSet(object.alreadyDeleted)
        ? globalThis.Boolean(object.alreadyDeleted)
        : isSet(object.already_deleted)
        ? globalThis.Boolean(object.already_deleted)
        : false,
      appliedRetirementFence: isSet(object.appliedRetirementFence)
        ? Fence.fromJSON(object.appliedRetirementFence)
        : isSet(object.applied_retirement_fence)
        ? Fence.fromJSON(object.applied_retirement_fence)
        : undefined,
    };
  },

  toJSON(message: HostDeleteResponse): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.alreadyDeleted !== false) {
      obj.alreadyDeleted = message.alreadyDeleted;
    }
    if (message.appliedRetirementFence !== undefined) {
      obj.appliedRetirementFence = Fence.toJSON(message.appliedRetirementFence);
    }
    return obj;
  },

  create(base?: DeepPartial<HostDeleteResponse>): HostDeleteResponse {
    return HostDeleteResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostDeleteResponse>): HostDeleteResponse {
    const message = createBaseHostDeleteResponse();
    message.sandboxId = object.sandboxId ?? "";
    message.alreadyDeleted = object.alreadyDeleted ?? false;
    message.appliedRetirementFence =
      (object.appliedRetirementFence !== undefined && object.appliedRetirementFence !== null)
        ? Fence.fromPartial(object.appliedRetirementFence)
        : undefined;
    return message;
  },
};

function createBaseHostCreatePreviewRequest(): HostCreatePreviewRequest {
  return { tenantId: "", sandboxId: "", hostId: "", previewId: "", port: 0, authMode: 0, name: "", idempotencyKey: "" };
}

export const HostCreatePreviewRequest: MessageFns<HostCreatePreviewRequest> = {
  encode(message: HostCreatePreviewRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    if (message.previewId !== "") {
      writer.uint32(34).string(message.previewId);
    }
    if (message.port !== 0) {
      writer.uint32(40).uint32(message.port);
    }
    if (message.authMode !== 0) {
      writer.uint32(48).int32(message.authMode);
    }
    if (message.name !== "") {
      writer.uint32(58).string(message.name);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(66).string(message.idempotencyKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostCreatePreviewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostCreatePreviewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.previewId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.port = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.authMode = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostCreatePreviewRequest {
    return {
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
      previewId: isSet(object.previewId)
        ? globalThis.String(object.previewId)
        : isSet(object.preview_id)
        ? globalThis.String(object.preview_id)
        : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      authMode: isSet(object.authMode)
        ? previewAuthModeFromJSON(object.authMode)
        : isSet(object.auth_mode)
        ? previewAuthModeFromJSON(object.auth_mode)
        : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      idempotencyKey: isSet(object.idempotencyKey)
        ? globalThis.String(object.idempotencyKey)
        : isSet(object.idempotency_key)
        ? globalThis.String(object.idempotency_key)
        : "",
    };
  },

  toJSON(message: HostCreatePreviewRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    if (message.previewId !== "") {
      obj.previewId = message.previewId;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.authMode !== 0) {
      obj.authMode = previewAuthModeToJSON(message.authMode);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    return obj;
  },

  create(base?: DeepPartial<HostCreatePreviewRequest>): HostCreatePreviewRequest {
    return HostCreatePreviewRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostCreatePreviewRequest>): HostCreatePreviewRequest {
    const message = createBaseHostCreatePreviewRequest();
    message.tenantId = object.tenantId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.hostId = object.hostId ?? "";
    message.previewId = object.previewId ?? "";
    message.port = object.port ?? 0;
    message.authMode = object.authMode ?? 0;
    message.name = object.name ?? "";
    message.idempotencyKey = object.idempotencyKey ?? "";
    return message;
  },
};

function createBaseHostCreatePreviewResponse(): HostCreatePreviewResponse {
  return { preview: undefined };
}

export const HostCreatePreviewResponse: MessageFns<HostCreatePreviewResponse> = {
  encode(message: HostCreatePreviewResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.preview !== undefined) {
      PreviewRecord.encode(message.preview, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostCreatePreviewResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostCreatePreviewResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preview = PreviewRecord.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostCreatePreviewResponse {
    return { preview: isSet(object.preview) ? PreviewRecord.fromJSON(object.preview) : undefined };
  },

  toJSON(message: HostCreatePreviewResponse): unknown {
    const obj: any = {};
    if (message.preview !== undefined) {
      obj.preview = PreviewRecord.toJSON(message.preview);
    }
    return obj;
  },

  create(base?: DeepPartial<HostCreatePreviewResponse>): HostCreatePreviewResponse {
    return HostCreatePreviewResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostCreatePreviewResponse>): HostCreatePreviewResponse {
    const message = createBaseHostCreatePreviewResponse();
    message.preview = (object.preview !== undefined && object.preview !== null)
      ? PreviewRecord.fromPartial(object.preview)
      : undefined;
    return message;
  },
};

function createBaseHostDeletePreviewRequest(): HostDeletePreviewRequest {
  return { tenantId: "", sandboxId: "", hostId: "", previewId: "" };
}

export const HostDeletePreviewRequest: MessageFns<HostDeletePreviewRequest> = {
  encode(message: HostDeletePreviewRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    if (message.previewId !== "") {
      writer.uint32(34).string(message.previewId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostDeletePreviewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostDeletePreviewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.previewId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostDeletePreviewRequest {
    return {
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
      previewId: isSet(object.previewId)
        ? globalThis.String(object.previewId)
        : isSet(object.preview_id)
        ? globalThis.String(object.preview_id)
        : "",
    };
  },

  toJSON(message: HostDeletePreviewRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    if (message.previewId !== "") {
      obj.previewId = message.previewId;
    }
    return obj;
  },

  create(base?: DeepPartial<HostDeletePreviewRequest>): HostDeletePreviewRequest {
    return HostDeletePreviewRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostDeletePreviewRequest>): HostDeletePreviewRequest {
    const message = createBaseHostDeletePreviewRequest();
    message.tenantId = object.tenantId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.hostId = object.hostId ?? "";
    message.previewId = object.previewId ?? "";
    return message;
  },
};

function createBaseHostDeletePreviewResponse(): HostDeletePreviewResponse {
  return { previewId: "", alreadyDeleted: false };
}

export const HostDeletePreviewResponse: MessageFns<HostDeletePreviewResponse> = {
  encode(message: HostDeletePreviewResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.previewId !== "") {
      writer.uint32(10).string(message.previewId);
    }
    if (message.alreadyDeleted !== false) {
      writer.uint32(16).bool(message.alreadyDeleted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostDeletePreviewResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostDeletePreviewResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.previewId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.alreadyDeleted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostDeletePreviewResponse {
    return {
      previewId: isSet(object.previewId)
        ? globalThis.String(object.previewId)
        : isSet(object.preview_id)
        ? globalThis.String(object.preview_id)
        : "",
      alreadyDeleted: isSet(object.alreadyDeleted)
        ? globalThis.Boolean(object.alreadyDeleted)
        : isSet(object.already_deleted)
        ? globalThis.Boolean(object.already_deleted)
        : false,
    };
  },

  toJSON(message: HostDeletePreviewResponse): unknown {
    const obj: any = {};
    if (message.previewId !== "") {
      obj.previewId = message.previewId;
    }
    if (message.alreadyDeleted !== false) {
      obj.alreadyDeleted = message.alreadyDeleted;
    }
    return obj;
  },

  create(base?: DeepPartial<HostDeletePreviewResponse>): HostDeletePreviewResponse {
    return HostDeletePreviewResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostDeletePreviewResponse>): HostDeletePreviewResponse {
    const message = createBaseHostDeletePreviewResponse();
    message.previewId = object.previewId ?? "";
    message.alreadyDeleted = object.alreadyDeleted ?? false;
    return message;
  },
};

function createBaseHostListPreviewsRequest(): HostListPreviewsRequest {
  return { tenantId: "", sandboxId: "", hostId: "" };
}

export const HostListPreviewsRequest: MessageFns<HostListPreviewsRequest> = {
  encode(message: HostListPreviewsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.hostId !== "") {
      writer.uint32(26).string(message.hostId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostListPreviewsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostListPreviewsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostListPreviewsRequest {
    return {
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      hostId: isSet(object.hostId)
        ? globalThis.String(object.hostId)
        : isSet(object.host_id)
        ? globalThis.String(object.host_id)
        : "",
    };
  },

  toJSON(message: HostListPreviewsRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.hostId !== "") {
      obj.hostId = message.hostId;
    }
    return obj;
  },

  create(base?: DeepPartial<HostListPreviewsRequest>): HostListPreviewsRequest {
    return HostListPreviewsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostListPreviewsRequest>): HostListPreviewsRequest {
    const message = createBaseHostListPreviewsRequest();
    message.tenantId = object.tenantId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.hostId = object.hostId ?? "";
    return message;
  },
};

function createBaseHostListPreviewsResponse(): HostListPreviewsResponse {
  return { previews: [] };
}

export const HostListPreviewsResponse: MessageFns<HostListPreviewsResponse> = {
  encode(message: HostListPreviewsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.previews) {
      PreviewRecord.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostListPreviewsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostListPreviewsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.previews.push(PreviewRecord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostListPreviewsResponse {
    return {
      previews: globalThis.Array.isArray(object?.previews)
        ? object.previews.map((e: any) => PreviewRecord.fromJSON(e))
        : [],
    };
  },

  toJSON(message: HostListPreviewsResponse): unknown {
    const obj: any = {};
    if (message.previews?.length) {
      obj.previews = message.previews.map((e) => PreviewRecord.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<HostListPreviewsResponse>): HostListPreviewsResponse {
    return HostListPreviewsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HostListPreviewsResponse>): HostListPreviewsResponse {
    const message = createBaseHostListPreviewsResponse();
    message.previews = object.previews?.map((e) => PreviewRecord.fromPartial(e)) || [];
    return message;
  },
};

export type HostServiceService = typeof HostServiceService;
export const HostServiceService = {
  create: {
    path: "/tyto.runtime.v1.HostService/Create" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateRequest): Buffer => Buffer.from(CreateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateRequest => CreateRequest.decode(value),
    responseSerialize: (value: CreateResponse): Buffer => Buffer.from(CreateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateResponse => CreateResponse.decode(value),
  },
  suspendSandbox: {
    path: "/tyto.runtime.v1.HostService/SuspendSandbox" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HostSuspendRequest): Buffer => Buffer.from(HostSuspendRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HostSuspendRequest => HostSuspendRequest.decode(value),
    responseSerialize: (value: HostSuspendResponse): Buffer => Buffer.from(HostSuspendResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HostSuspendResponse => HostSuspendResponse.decode(value),
  },
  resumeSandbox: {
    path: "/tyto.runtime.v1.HostService/ResumeSandbox" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HostResumeRequest): Buffer => Buffer.from(HostResumeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HostResumeRequest => HostResumeRequest.decode(value),
    responseSerialize: (value: HostResumeResponse): Buffer => Buffer.from(HostResumeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HostResumeResponse => HostResumeResponse.decode(value),
  },
  createSnapshot: {
    path: "/tyto.runtime.v1.HostService/CreateSnapshot" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HostCreateSnapshotRequest): Buffer =>
      Buffer.from(HostCreateSnapshotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HostCreateSnapshotRequest => HostCreateSnapshotRequest.decode(value),
    responseSerialize: (value: HostCreateSnapshotResponse): Buffer =>
      Buffer.from(HostCreateSnapshotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HostCreateSnapshotResponse => HostCreateSnapshotResponse.decode(value),
  },
  deleteSnapshot: {
    path: "/tyto.runtime.v1.HostService/DeleteSnapshot" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HostDeleteSnapshotRequest): Buffer =>
      Buffer.from(HostDeleteSnapshotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HostDeleteSnapshotRequest => HostDeleteSnapshotRequest.decode(value),
    responseSerialize: (value: HostDeleteSnapshotResponse): Buffer =>
      Buffer.from(HostDeleteSnapshotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HostDeleteSnapshotResponse => HostDeleteSnapshotResponse.decode(value),
  },
  deleteSandbox: {
    path: "/tyto.runtime.v1.HostService/DeleteSandbox" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HostDeleteRequest): Buffer => Buffer.from(HostDeleteRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HostDeleteRequest => HostDeleteRequest.decode(value),
    responseSerialize: (value: HostDeleteResponse): Buffer => Buffer.from(HostDeleteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HostDeleteResponse => HostDeleteResponse.decode(value),
  },
  createPreview: {
    path: "/tyto.runtime.v1.HostService/CreatePreview" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HostCreatePreviewRequest): Buffer =>
      Buffer.from(HostCreatePreviewRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HostCreatePreviewRequest => HostCreatePreviewRequest.decode(value),
    responseSerialize: (value: HostCreatePreviewResponse): Buffer =>
      Buffer.from(HostCreatePreviewResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HostCreatePreviewResponse => HostCreatePreviewResponse.decode(value),
  },
  deletePreview: {
    path: "/tyto.runtime.v1.HostService/DeletePreview" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HostDeletePreviewRequest): Buffer =>
      Buffer.from(HostDeletePreviewRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HostDeletePreviewRequest => HostDeletePreviewRequest.decode(value),
    responseSerialize: (value: HostDeletePreviewResponse): Buffer =>
      Buffer.from(HostDeletePreviewResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HostDeletePreviewResponse => HostDeletePreviewResponse.decode(value),
  },
  listPreviews: {
    path: "/tyto.runtime.v1.HostService/ListPreviews" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HostListPreviewsRequest): Buffer =>
      Buffer.from(HostListPreviewsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HostListPreviewsRequest => HostListPreviewsRequest.decode(value),
    responseSerialize: (value: HostListPreviewsResponse): Buffer =>
      Buffer.from(HostListPreviewsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HostListPreviewsResponse => HostListPreviewsResponse.decode(value),
  },
} as const;

export interface HostServiceServer extends UntypedServiceImplementation {
  create: handleUnaryCall<CreateRequest, CreateResponse>;
  suspendSandbox: handleUnaryCall<HostSuspendRequest, HostSuspendResponse>;
  resumeSandbox: handleUnaryCall<HostResumeRequest, HostResumeResponse>;
  createSnapshot: handleUnaryCall<HostCreateSnapshotRequest, HostCreateSnapshotResponse>;
  deleteSnapshot: handleUnaryCall<HostDeleteSnapshotRequest, HostDeleteSnapshotResponse>;
  deleteSandbox: handleUnaryCall<HostDeleteRequest, HostDeleteResponse>;
  createPreview: handleUnaryCall<HostCreatePreviewRequest, HostCreatePreviewResponse>;
  deletePreview: handleUnaryCall<HostDeletePreviewRequest, HostDeletePreviewResponse>;
  listPreviews: handleUnaryCall<HostListPreviewsRequest, HostListPreviewsResponse>;
}

export interface HostServiceClient extends Client {
  create(
    request: CreateRequest,
    callback: (error: ServiceError | null, response: CreateResponse) => void,
  ): ClientUnaryCall;
  create(
    request: CreateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateResponse) => void,
  ): ClientUnaryCall;
  create(
    request: CreateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateResponse) => void,
  ): ClientUnaryCall;
  suspendSandbox(
    request: HostSuspendRequest,
    callback: (error: ServiceError | null, response: HostSuspendResponse) => void,
  ): ClientUnaryCall;
  suspendSandbox(
    request: HostSuspendRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HostSuspendResponse) => void,
  ): ClientUnaryCall;
  suspendSandbox(
    request: HostSuspendRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HostSuspendResponse) => void,
  ): ClientUnaryCall;
  resumeSandbox(
    request: HostResumeRequest,
    callback: (error: ServiceError | null, response: HostResumeResponse) => void,
  ): ClientUnaryCall;
  resumeSandbox(
    request: HostResumeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HostResumeResponse) => void,
  ): ClientUnaryCall;
  resumeSandbox(
    request: HostResumeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HostResumeResponse) => void,
  ): ClientUnaryCall;
  createSnapshot(
    request: HostCreateSnapshotRequest,
    callback: (error: ServiceError | null, response: HostCreateSnapshotResponse) => void,
  ): ClientUnaryCall;
  createSnapshot(
    request: HostCreateSnapshotRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HostCreateSnapshotResponse) => void,
  ): ClientUnaryCall;
  createSnapshot(
    request: HostCreateSnapshotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HostCreateSnapshotResponse) => void,
  ): ClientUnaryCall;
  deleteSnapshot(
    request: HostDeleteSnapshotRequest,
    callback: (error: ServiceError | null, response: HostDeleteSnapshotResponse) => void,
  ): ClientUnaryCall;
  deleteSnapshot(
    request: HostDeleteSnapshotRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HostDeleteSnapshotResponse) => void,
  ): ClientUnaryCall;
  deleteSnapshot(
    request: HostDeleteSnapshotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HostDeleteSnapshotResponse) => void,
  ): ClientUnaryCall;
  deleteSandbox(
    request: HostDeleteRequest,
    callback: (error: ServiceError | null, response: HostDeleteResponse) => void,
  ): ClientUnaryCall;
  deleteSandbox(
    request: HostDeleteRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HostDeleteResponse) => void,
  ): ClientUnaryCall;
  deleteSandbox(
    request: HostDeleteRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HostDeleteResponse) => void,
  ): ClientUnaryCall;
  createPreview(
    request: HostCreatePreviewRequest,
    callback: (error: ServiceError | null, response: HostCreatePreviewResponse) => void,
  ): ClientUnaryCall;
  createPreview(
    request: HostCreatePreviewRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HostCreatePreviewResponse) => void,
  ): ClientUnaryCall;
  createPreview(
    request: HostCreatePreviewRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HostCreatePreviewResponse) => void,
  ): ClientUnaryCall;
  deletePreview(
    request: HostDeletePreviewRequest,
    callback: (error: ServiceError | null, response: HostDeletePreviewResponse) => void,
  ): ClientUnaryCall;
  deletePreview(
    request: HostDeletePreviewRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HostDeletePreviewResponse) => void,
  ): ClientUnaryCall;
  deletePreview(
    request: HostDeletePreviewRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HostDeletePreviewResponse) => void,
  ): ClientUnaryCall;
  listPreviews(
    request: HostListPreviewsRequest,
    callback: (error: ServiceError | null, response: HostListPreviewsResponse) => void,
  ): ClientUnaryCall;
  listPreviews(
    request: HostListPreviewsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HostListPreviewsResponse) => void,
  ): ClientUnaryCall;
  listPreviews(
    request: HostListPreviewsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HostListPreviewsResponse) => void,
  ): ClientUnaryCall;
}

export const HostServiceClient = makeGenericClientConstructor(
  HostServiceService,
  "tyto.runtime.v1.HostService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): HostServiceClient;
  service: typeof HostServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
