// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v6.33.4
// source: tyto/runtime/v1/preview.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tyto.runtime.v1";

/** PreviewAuthMode is how a preview URL admits a request. */
export enum PreviewAuthMode {
  /**
   * PREVIEW_AUTH_MODE_UNSPECIFIED - Unset. Callers must choose; the server treats this as TOKEN rather than
   * guessing, so a client that forgets the field gets the safe mode.
   */
  PREVIEW_AUTH_MODE_UNSPECIFIED = 0,
  /**
   * PREVIEW_AUTH_MODE_TOKEN - The sandbox's data-plane capability admits the request, as a bearer token
   * or via the browser exchange flow.
   */
  PREVIEW_AUTH_MODE_TOKEN = 1,
  /**
   * PREVIEW_AUTH_MODE_PUBLIC - No authentication: anyone holding the URL reaches the service. Explicit
   * opt-in only, never a default.
   */
  PREVIEW_AUTH_MODE_PUBLIC = 2,
}

export function previewAuthModeFromJSON(object: any): PreviewAuthMode {
  switch (object) {
    case 0:
    case "PREVIEW_AUTH_MODE_UNSPECIFIED":
      return PreviewAuthMode.PREVIEW_AUTH_MODE_UNSPECIFIED;
    case 1:
    case "PREVIEW_AUTH_MODE_TOKEN":
      return PreviewAuthMode.PREVIEW_AUTH_MODE_TOKEN;
    case 2:
    case "PREVIEW_AUTH_MODE_PUBLIC":
      return PreviewAuthMode.PREVIEW_AUTH_MODE_PUBLIC;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum PreviewAuthMode");
  }
}

export function previewAuthModeToJSON(object: PreviewAuthMode): string {
  switch (object) {
    case PreviewAuthMode.PREVIEW_AUTH_MODE_UNSPECIFIED:
      return "PREVIEW_AUTH_MODE_UNSPECIFIED";
    case PreviewAuthMode.PREVIEW_AUTH_MODE_TOKEN:
      return "PREVIEW_AUTH_MODE_TOKEN";
    case PreviewAuthMode.PREVIEW_AUTH_MODE_PUBLIC:
      return "PREVIEW_AUTH_MODE_PUBLIC";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum PreviewAuthMode");
  }
}

/** PreviewRecord is one preview binding, without its URL. */
export interface PreviewRecord {
  /**
   * preview_id is the routing identity, minted by TApi: pv- followed by 26
   * lowercase base32 characters. It is a DNS label, and in public mode its
   * entropy is the only guard besides TLS.
   */
  previewId: string;
  sandboxId: string;
  /**
   * port is the guest port this preview reaches, 1024-65535. Privileged ports
   * are excluded so a preview can never hand out a guest's ssh.
   */
  port: number;
  authMode: PreviewAuthMode;
  /**
   * name is display metadata only and is never part of the URL, so renaming a
   * preview cannot move it.
   */
  name: string;
  createdAtUnixNanos: number;
}

function createBasePreviewRecord(): PreviewRecord {
  return { previewId: "", sandboxId: "", port: 0, authMode: 0, name: "", createdAtUnixNanos: 0 };
}

export const PreviewRecord: MessageFns<PreviewRecord> = {
  encode(message: PreviewRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.previewId !== "") {
      writer.uint32(10).string(message.previewId);
    }
    if (message.sandboxId !== "") {
      writer.uint32(18).string(message.sandboxId);
    }
    if (message.port !== 0) {
      writer.uint32(24).uint32(message.port);
    }
    if (message.authMode !== 0) {
      writer.uint32(32).int32(message.authMode);
    }
    if (message.name !== "") {
      writer.uint32(42).string(message.name);
    }
    if (message.createdAtUnixNanos !== 0) {
      writer.uint32(48).int64(message.createdAtUnixNanos);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PreviewRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePreviewRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.previewId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.port = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.authMode = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.createdAtUnixNanos = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PreviewRecord {
    return {
      previewId: isSet(object.previewId)
        ? globalThis.String(object.previewId)
        : isSet(object.preview_id)
        ? globalThis.String(object.preview_id)
        : "",
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
        ? globalThis.String(object.sandbox_id)
        : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      authMode: isSet(object.authMode)
        ? previewAuthModeFromJSON(object.authMode)
        : isSet(object.auth_mode)
        ? previewAuthModeFromJSON(object.auth_mode)
        : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      createdAtUnixNanos: isSet(object.createdAtUnixNanos)
        ? globalThis.Number(object.createdAtUnixNanos)
        : isSet(object.created_at_unix_nanos)
        ? globalThis.Number(object.created_at_unix_nanos)
        : 0,
    };
  },

  toJSON(message: PreviewRecord): unknown {
    const obj: any = {};
    if (message.previewId !== "") {
      obj.previewId = message.previewId;
    }
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.authMode !== 0) {
      obj.authMode = previewAuthModeToJSON(message.authMode);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.createdAtUnixNanos !== 0) {
      obj.createdAtUnixNanos = Math.round(message.createdAtUnixNanos);
    }
    return obj;
  },

  create(base?: DeepPartial<PreviewRecord>): PreviewRecord {
    return PreviewRecord.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PreviewRecord>): PreviewRecord {
    const message = createBasePreviewRecord();
    message.previewId = object.previewId ?? "";
    message.sandboxId = object.sandboxId ?? "";
    message.port = object.port ?? 0;
    message.authMode = object.authMode ?? 0;
    message.name = object.name ?? "";
    message.createdAtUnixNanos = object.createdAtUnixNanos ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
